[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/vendedor"
  to = "/vendedor.html"
  status = 200

[[redirects]]
  from = "/cliente"
  to = "/cliente.html"
  status = 200

[[redirects]]
  from = "/cadastro"
  to = "/cadastro.html"
  status = 200

[[redirects]]
  from = "/termo"
  to = "/termo.html"
  status = 200

[[redirects]]
  from = "/contrato"
  to = "/contrato.html"
  status = 200

[[redirects]]
  from = "/recibo"
  to = "/recibo.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "camera=*, microphone=()"
